### ISSUE TITLE
Add support for quoted CSV files

### ISSUE THREAD

**Issue by d33tah** [ProfoundNetworks/csvinsight#11]
I just noticed that csvinsight reports that some of columns in my file contain an unexpected number of columns. I inspected the file and it looks like those are quoted, which doesn't seem to be supported yet. Could you add optional `-q` that sets `quotechar` in `_open_csv` in cli.py? Because of `unicode_numerals`, it might require something like `args.quotechar.encode('utf8')`.

**Comment by mpenkov** [comment]
You can now use the --dialect command-line flag to specify CSV dialect options.
