### ISSUE TITLE
Add short options for --file and --delimiter

### ISSUE THREAD

**Issue by d33tah** [ProfoundNetworks/csvinsight#9]
It would be nice to have short options for commonly used options, such as `--delimiter` and `--file`. My suggestion is to introduce `-d` and `-i` options (or `-f`, though `-i` seems to follow the UNIX convention more).

**Comment by mpenkov** [comment]
The path to the input file is now a positional argument.

--delimiter now gets specified as part the CSV --dialect or the config file.
